**Step-by-step Guidence on How to Install and Use ADBench**

# Install ADBench

In [1]:
%load_ext autoreload
%reload_ext autoreload
%autoreload 2

In [2]:
# download datasets in ADBench from the remote github repo
from adbench.myutils import Utils
utils = Utils()
# we recommend jihulab for China mainland user and github otherwise
#utils.download_datasets(repo='github')

# Run ADBench 

## Run ADBench experiments

In [3]:
from adbench.run import RunPipeline

'''
Params:
suffix: file name suffix;

parallel: running either 'unsupervise', 'semi-supervise', or 'supervise' (AD) algorithms,
corresponding to the Angle I: Availability of Ground Truth Labels (Supervision);

realistic_synthetic_mode: testing on 'local', 'global', 'dependency', and 'cluster' anomalies, 
corresponding to the Angle II: Types of Anomalies;

noise type: evaluating algorithms on 'duplicated_anomalies', 'irrelevant_features' and 'label_contamination',
corresponding to the Angle III: Model Robustness with Noisy and Corrupted Data.
'''

"\nParams:\nsuffix: file name suffix;\n\nparallel: running either 'unsupervise', 'semi-supervise', or 'supervise' (AD) algorithms,\ncorresponding to the Angle I: Availability of Ground Truth Labels (Supervision);\n\nrealistic_synthetic_mode: testing on 'local', 'global', 'dependency', and 'cluster' anomalies, \ncorresponding to the Angle II: Types of Anomalies;\n\nnoise type: evaluating algorithms on 'duplicated_anomalies', 'irrelevant_features' and 'label_contamination',\ncorresponding to the Angle III: Model Robustness with Noisy and Corrupted Data.\n"

In [4]:
#pipeline = RunPipeline(suffix='ADBench', parallel='unsupervise', realistic_synthetic_mode='cluster', noise_type=None)
#results = pipeline.run()

In [5]:
#pipeline = RunPipeline(suffix='ADBench', parallel='supervise', realistic_synthetic_mode=None, noise_type='irrelevant_features')
#results = pipeline.run()

## Run your customized algorithm on ADBench datasets

In [6]:
# customized model on ADBench's datasets
from adbench.run import RunPipeline
from adbench.baseline.SimpleAE.run import SimpleAE
from adbench.baseline.VAE.run import VAE
from adbench.baseline.DOCAE.run import DOCAE
from adbench.baseline.AADOCAE.run import AADOCAE

# notice that you should specify the corresponding category of your customized AD algorithm
# for example, here we use Logistic Regression as customized clf, which belongs to the supervised algorithm
# for your own algorithm, you can realize the same usage as other baselines by modifying the fit.py, model.py, and run.py files in the adbench/baseline/Customized
pipeline = RunPipeline(suffix='ADBench', parallel='unsupervise', realistic_synthetic_mode=None, noise_type=None, num_seed=3)

## Run ADBench algos on all datasets with every kinds of synthetic anomalies (unsupervised) 

epoch : 1/3000, loss = 1487.138672
epoch : 100/3000, loss = 10.363136
epoch : 200/3000, loss = 2.878419
epoch : 300/3000, loss = 2.028150
epoch : 400/3000, loss = 1.230358
epoch : 500/3000, loss = 1.005102
epoch : 600/3000, loss = 0.697317
epoch : 700/3000, loss = 0.598053
epoch : 800/3000, loss = 0.733529
epoch : 900/3000, loss = 5.462417
epoch : 1000/3000, loss = 0.432301
epoch : 1100/3000, loss = 0.493422
epoch : 1200/3000, loss = 0.384208
epoch : 1300/3000, loss = 0.371852
epoch : 1400/3000, loss = 0.322503
epoch : 1500/3000, loss = 0.389983
epoch : 1600/3000, loss = 0.384546
epoch : 1700/3000, loss = 0.484489
epoch : 1800/3000, loss = 0.672034
epoch : 1900/3000, loss = 0.854956
epoch : 2000/3000, loss = 0.265423
epoch : 2100/3000, loss = 0.451732
epoch : 2200/3000, loss = 0.374019
epoch : 2300/3000, loss = 0.538315
epoch : 2400/3000, loss = 0.618200
epoch : 2500/3000, loss = 0.277787
epoch : 2600/3000, loss = 0.199320
epoch : 2700/3000, loss = 0.215055
epoch : 2800/3000, loss = 0.177954
epoch : 2900/3000, loss = 0.276497

In [9]:
for mode in [
                #None,
                'dependency',
                'cluster',
                None,
                'local',
                'global',
            ]:
    pipeline = RunPipeline(suffix='ADBench', parallel='unsupervise', realistic_synthetic_mode=mode, noise_type=None, num_seed=3)
    #results = pipeline.run(clf=VAE)
    results = pipeline.run(clf=AADOCAE)

{'Samples': 10000, 'Features': 10, 'Anomalies': 97, 'Anomalies Ratio(%)': 0.97}
{'Samples': 10000, 'Features': 10, 'Anomalies': 116, 'Anomalies Ratio(%)': 1.16}
{'Samples': 10000, 'Features': 10, 'Anomalies': 95, 'Anomalies Ratio(%)': 0.95}
{'Samples': 10000, 'Features': 10, 'Anomalies': 618, 'Anomalies Ratio(%)': 6.18}
{'Samples': 10000, 'Features': 10, 'Anomalies': 578, 'Anomalies Ratio(%)': 5.78}
{'Samples': 10000, 'Features': 10, 'Anomalies': 597, 'Anomalies Ratio(%)': 5.97}
{'Samples': 1941, 'Features': 27, 'Anomalies': 673, 'Anomalies Ratio(%)': 34.67}
{'Samples': 1941, 'Features': 27, 'Anomalies': 673, 'Anomalies Ratio(%)': 34.67}
{'Samples': 1941, 'Features': 27, 'Anomalies': 673, 'Anomalies Ratio(%)': 34.67}
{'Samples': 10000, 'Features': 29, 'Anomalies': 15, 'Anomalies Ratio(%)': 0.15}
{'Samples': 10000, 'Features': 29, 'Anomalies': 15, 'Anomalies Ratio(%)': 0.15}
{'Samples': 10000, 'Features': 29, 'Anomalies': 13, 'Anomalies Ratio(%)': 0.13}
{'Samples': 1000, 'Features': 7, 

0it [00:00, ?it/s]

{'Samples': 2000, 'Features': 9, 'Anomalies': 178, 'Anomalies Ratio(%)': 8.9}


TypeError: 'float' object cannot be interpreted as an integer

In [ ]:
for mode in ['cluster',
            'local',
            'global',
            'dependency',
            None,
            ]:
    pipeline = RunPipeline(suffix='ADBench', parallel='unsupervise', realistic_synthetic_mode=mode, noise_type=None, num_seed=1)
    #results = pipeline.run(clf=VAE)
    results = pipeline.run(clf=DOCAE)

## Run your customized algorithm on customized dataset

In [ ]:
from adbench.baseline.Bagging.run import Bagging
from adbench.baseline.AADOCAE.run import AADOCAE

In [ ]:
# customized model on customized dataset
import numpy as np
dataset = {}
dataset['X'] = np.random.randn(1000, 20)
dataset['y'] = np.random.choice([0, 1], 1000)
#print(dataset['y'])
RunPipeline(suffix='ADBench', parallel='unsupervise', realistic_synthetic_mode=None, noise_type=None, num_seed=1)
results = pipeline.run(dataset=dataset, clf=AADOCAE)


0it [00:00, ?it/s]

Testing on customized dataset...
{'Samples': 1000, 'Features': 20, 'Anomalies': 498, 'Anomalies Ratio(%)': 49.8}
epoch : 1/12, loss = 5.524560
self.error_median=3.8629, self.error_range=0.8937, self.latent_error_median_=0.6489, self.latent_error_range_=0.1544
Model result scaling scheme:  True
Latent dim= 16. Weight Decay = 0.000001
Using cuda
self.error_mu=3.8807, self.error_std=0.5358, self.latent_error_mu_=0.6518, self.latent_error_sigma_=0.0945; alpha = 1.0000
Current experiment parameters: (None, 0.0, 1), model: Customized, metrics: {'aucroc': 0.4888661718298591, 'aucpr': 0.48867482615817526}, fitting time: 0.2572813034057617, inference time: 0.0019817352294921875


1it [00:00,  1.69it/s]


Model performance:
Reconstruction AUCROC=0.5086; AUCPR=0.5066
Deviation AUCROC=0.4798; AUCPR=0.4729
Max(rec, dev) AUCROC=0.5086; AUCPR=0.5066

Sum of squared error AUCROC=0.5076; AUCPR=0.5058

Testing on customized dataset...
{'Samples': 1000, 'Features': 20, 'Anomalies': 498, 'Anomalies Ratio(%)': 49.8}
epoch : 1/12, loss = 5.673854
self.error_median=5.0582, self.error_range=1.1281, self.latent_error_median_=0.1390, self.latent_error_range_=0.0487
Model result scaling scheme:  True
Latent dim= 16. Weight Decay = 0.000001
Using cuda
self.error_mu=5.0629, self.error_std=0.6781, self.latent_error_mu_=0.1409, self.latent_error_sigma_=0.0290; alpha = 1.0000


2it [00:00,  2.09it/s]

Current experiment parameters: (None, 0.0, 2), model: Customized, metrics: {'aucroc': 0.4651317836348282, 'aucpr': 0.47213899486085287}, fitting time: 0.17455291748046875, inference time: 0.0019958019256591797

Model performance:
Reconstruction AUCROC=0.4769; AUCPR=0.4771
Deviation AUCROC=0.4565; AUCPR=0.4785
Max(rec, dev) AUCROC=0.4769; AUCPR=0.4771

Sum of squared error AUCROC=0.4769; AUCPR=0.4770

Testing on customized dataset...
{'Samples': 1000, 'Features': 20, 'Anomalies': 498, 'Anomalies Ratio(%)': 49.8}
epoch : 1/12, loss = 5.687943
self.error_median=4.8010, self.error_range=1.0662, self.latent_error_median_=0.2704, self.latent_error_range_=0.0737
Model result scaling scheme:  True
Latent dim= 16. Weight Decay = 0.000001
Using cuda
self.error_mu=4.8202, self.error_std=0.6516, self.latent_error_mu_=0.2692, self.latent_error_sigma_=0.0447; alpha = 1.0000


24it [00:01, 17.05it/s]

Current experiment parameters: (None, 0.0, 3), model: Customized, metrics: {'aucroc': 0.5135783812613894, 'aucpr': 0.5175445014161114}, fitting time: 0.17716336250305176, inference time: 0.0019948482513427734

Model performance:
Reconstruction AUCROC=0.5043; AUCPR=0.4993
Deviation AUCROC=0.5219; AUCPR=0.5329
Max(rec, dev) AUCROC=0.5043; AUCPR=0.4993

Sum of squared error AUCROC=0.5044; AUCPR=0.4993



# Import AD algorithms from ADBench

In [ ]:
import numpy as np
X_train = np.random.randn(1000, 1)
X_train = np.concatenate((X_train, X_train, X_train, X_train), axis=-1)
y_train = np.random.choice([0, 1], 1000)
X_test = np.random.randn(100, 4)
y_test = np.random.choice([0, 1], 100)

# Directly import AD algorithms from the existing toolkits like PyOD
#from adbench.baseline.PyOD import PYOD
#model = PYOD(seed=42, model_name='XGBOD')  # initialization
model = SimpleAE(seed=42)
model.fit(X_train, y_train)  # fit
score = model.predict_score(X_test)  # predict
print(score.shape)

# Import deep learning AD algorithms from our ADBench
""" from adbench.baseline.PReNet.run import PReNet
model = PReNet(seed=42)
model.fit(X_train, y_train)  # fit
score = model.predict_score(X_test)  # predict """

fit transform: X shape before:  (1000, 4)
[[0. 1. 1. 1.]
 [1. 0. 1. 1.]
 [1. 1. 0. 1.]
 [1. 1. 1. 0.]]
Train data shape after filter corrcoef:  (1000, 1)
epoch : 1000/3000, loss = 1.000339
epoch : 2000/3000, loss = 1.000902
epoch : 3000/3000, loss = 1.001148
(100, 1)


' from adbench.baseline.PReNet.run import PReNet\nmodel = PReNet(seed=42)\nmodel.fit(X_train, y_train)  # fit\nscore = model.predict_score(X_test)  # predict '