In [1]:
%load_ext autoreload
%reload_ext autoreload
%autoreload 2

import torch

In [39]:
arr=[]
a = torch.rand((5, 2))
b = torch.rand((5, 2))
print(a)
print(b)
for _ in range(1):
    arr.append(a)
    arr.append(b)

arr = torch.concat(arr, dim=-1)
print(arr)
print(torch.nn.Softmax(dim=0)(arr.sum(dim=-1, keepdim=True)))
#arr = arr.reshape(-1, arr.shape[-1]*arr.shape[-2])
#print(arr)
#arr.shape
#torch.cuda.is_available()
#1.24.3

tensor([[0.5404, 0.0233],
        [0.3154, 0.5294],
        [0.6294, 0.2950],
        [0.8044, 0.8384],
        [0.7425, 0.6872]])
tensor([[0.7078, 0.3056],
        [0.9072, 0.4253],
        [0.4194, 0.0482],
        [0.2131, 0.5360],
        [0.7081, 0.5959]])
tensor([[0.5404, 0.0233, 0.7078, 0.3056],
        [0.3154, 0.5294, 0.9072, 0.4253],
        [0.6294, 0.2950, 0.4194, 0.0482],
        [0.8044, 0.8384, 0.2131, 0.5360],
        [0.7425, 0.6872, 0.7081, 0.5959]])
tensor([[0.1100],
        [0.2004],
        [0.0914],
        [0.2484],
        [0.3497]])
